# Generated by Django 5.0.1 on 2026-02-17 20:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='組織名')),
                ('org_type', models.CharField(choices=[('SCHOOL', '学校'), ('COMPANY', '企業')], max_length=20, verbose_name='組織種別')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '組織',
                'verbose_name_plural': '組織',
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('role', models.CharField(choices=[('ADMIN', '管理者'), ('USER', '一般ユーザー')], default='USER', max_length=20, verbose_name='権限')),
                ('is_activated', models.BooleanField(default=False, verbose_name='アカウント有効化済み')),
                ('full_name', models.CharField(max_length=100, verbose_name='氏名')),
                ('full_name_kana', models.CharField(blank=True, max_length=100, null=True, verbose_name='氏名カナ')),
                ('gender', models.CharField(blank=True, choices=[('MALE', '男性'), ('FEMALE', '女性'), ('OTHER', 'その他')], max_length=10, null=True, verbose_name='性別')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('employee_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='社員番号')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='部署・所属')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='役職')),
                ('student_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='学籍番号・出席番号')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='学年')),
                ('class_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='組・クラス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.organization', verbose_name='所属組織')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='InviteToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='トークン')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('is_used', models.BooleanField(default=False, verbose_name='使用済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to=settings.AUTH_USER_MODEL, verbose_name='招待されたユーザー')),
            ],
            options={
                'verbose_name': '招待トークン',
                'verbose_name_plural': '招待トークン',
                'db_table': 'invite_tokens',
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('GREEN', '健康'), ('YELLOW', '注意'), ('RED', '警告')], max_length=10, verbose_name='ステータス')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='記録日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ステータス記録',
                'verbose_name_plural': 'ステータス記録',
                'db_table': 'status_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='status_logs_user_id_d3d174_idx'), models.Index(fields=['status', '-created_at'], name='status_logs_status_e51b79_idx')],
            },
        ),
    ]
