# Generated by Django 5.0.1 on 2026-03-02 07:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitetoken',
            options={'verbose_name': '招待・リセットトークン', 'verbose_name_plural': '招待・リセットトークン'},
        ),
        migrations.AddField(
            model_name='invitetoken',
            name='token_type',
            field=models.CharField(choices=[('INVITE', '招待'), ('RESET', 'パスワードリセット')], default='INVITE', help_text='招待 or パスワードリセット', max_length=10, verbose_name='トークン種別'),
        ),
        migrations.AlterField(
            model_name='invitetoken',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='トークン'),
        ),
        migrations.AlterField(
            model_name='invitetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to=settings.AUTH_USER_MODEL, verbose_name='対象ユーザー'),
        ),
    ]
