# Generated by Django 5.0.1 on 2026-01-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='クラス'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='部署・チーム'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='社員番号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name_kana',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='氏名カナ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', '男性'), ('FEMALE', '女性'), ('OTHER', 'その他')], max_length=10, null=True, verbose_name='性別'),
        ),
    ]
