# Generated by Django - Updated User model fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        # 既存フィールドの調整
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='組・クラス'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='部署・所属'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='社員番号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name_kana',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='氏名カナ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', '男性'), ('FEMALE', '女性'), ('OTHER', 'その他')], max_length=10, null=True, verbose_name='性別'),
        ),
        
        # 新フィールド追加（attendance_numberは追加しない）
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='役職'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='学籍番号・出席番号'),
        ),
    ]
